FROM ubuntu:22.04 AS BUILD_IMAGE

LABEL maintainer="gramcha <gramcha@outlook.com>"

ENV BOOTSTRAP=bootstrap
ENV TZ=Etc/UTC
# important step to avoid interactive question of select timezone during installation
RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone
# update os and download required packages
RUN apt-get -y update && \
    apt-get -y dist-upgrade && \
    apt-get install -y sudo && \
    apt-get install -y curl && \
    apt-get install -y vim && \
    apt-get install -y wget && \
    apt-get install -y net-tools && \
    apt-get install -y lsof && \
    apt-get install -y unzip && \
    apt-get install -y nginx && \
    apt-get install -y rpl && \
    apt-get install bash-completion && \
    apt-get install -y uuid-runtime && \
    bash --version && \
    curl -sL https://deb.nodesource.com/setup_18.x | sudo bash - && \
    apt-get install -f --yes nodejs && \
    apt-get install -f --yes build-essential && \
    apt-get install -y weasyprint



# before calling the npm install work directory needs to be set from node 18
RUN mkdir /root/ubuntu-node-nginx/
ADD . /root/ubuntu-node-nginx/
WORKDIR /root/ubuntu-node-nginx/

# adding pm2 at global level since npx pm2 create "Cannot find module '/root/.npm/_npx/1286/lib/node_modules/pm2/lib/ProcessContainerFork.js'" error
# https://github.com/Unitech/pm2/issues/1943
# only fix working is having pm2 at global and avoiding the npx and install consul service
RUN npm install -g pm2 && \
    bash install-consul.sh && \
    bash install-yarn.sh && \
    chmod +x entrypoint.sh && \
    pm2 install pm2-logrotate && \
    pm2 set pm2-logrotate:max_size 10M

EXPOSE 80
EXPOSE 443

STOPSIGNAL SIGQUIT

COPY entrypoint.sh /root/ubuntu-node-nginx/

ENTRYPOINT ["/root/ubuntu-node-nginx/entrypoint.sh"]

CMD ["Hello", ", world!"]
